//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_articulo
    {
        public string id_articulo { get; set; }
        public string descripcion_articulo { get; set; }
        public System.DateTime ultima_compra { get; set; }
        public System.DateTime ultima_salida { get; set; }
        public int minimo { get; set; }
        public int maximo { get; set; }
        public int saldo { get; set; }
        public int id_inventario { get; set; }
    }
}
